class CfgPatches {
    class Overgrown_Weapon {
        units[]={};
        weapons[]={};
        requiredVersion=0.1;
        requiredAddons[]=
        {
            "DZ_Data"
        };
    };
};
class CfgVehicles {
    // Custom attachments!!
    // New Improvised Suppressor, cause why the fuck not
    class ImprovisedSuppressor;
    class WWB_ImprovisedSuppressor_Soda: ImprovisedSuppressor {
        displayName="Soda Suppressor";
        descriptionShort="An improvised muzzle device for firearms. Kinda reduces sound intensity and muzzle flash generated by firing. Very flimsy.";
        itemSize[]={1,2};
        model="\dz\gear\drinks\SodaCan.p3d";
        hiddenSelections[]={"zbytek"};
        hiddenSelectionsTextures[]=
        {
            "\Overgrown\data\weapon\firearm\ImprovisedSuppressor_Soda_co.paa"
        };
    };

    // More Melee shit
    class FireExtinguisher;
    class WWB_FireExtinguisher: FireExtinguisher {
        displayName="Fire Extinguisher";
        descriptionShort="The instructions read: 1. Hold upright. Pull ring pin. 2. Stand back 10 feet. Aim at base of fire. 3. Squeeze lever. 4. Sweep side to side. Dry chemical powder type.";
        itemSize[]={2,4};
    };
    class Sickle;
    class WWB_Sickle: Sickle {
        displayName="Sickle";
        descriptionShort="A hand-held agricultural tool with a curved blade typically used for harvesting grain crops or cutting dried grasses.";
        itemSize[]={2,3};
    };
    class HayHook;
    class WWB_HayHook: HayHook {
        displayName="Hay Hook";
        descriptionShort="A hand tool is used for securing and moving hay stacks. It consists of a round wooden handle with a strong metal hook.";
        itemSize[]={1,2};
    };
    class Mace;
    class WWB_Mace: Mace {
        displayName="Flanged Mace";
        descriptionShort="A blunt weapon, a type of club. Consists of a strong, heavy metal shaft, featuring a head made of steel.";
        itemSize[]={1,6};
        class MeleeModes {
            class Default {
                ammo="MeleeMace";
                range=1.4;
            };
        };
    };
    class Cleaver;
    class EG_Weapon_Cleaver: Cleaver {
        displayName="Cleaver";
        descriptionShort="A big, heavy and sharp knife designed to chop through thick raw meat. Can also crack bones easily.";
        itemSize[]={1,2};
    };
    class Sword;
    class EG_Weapon_Sword: Sword {
        displayName="Sword";
        descriptionShort="A faithful replica of a medieval sword.";
        itemSize[]={1,7};
    };
    class PoliceBaton;
    class EG_Weapon_PoliceBaton: PoliceBaton {
        displayName="Police Nightstick";
        descriptionShort="A short metal baton coated in rubber used a weapon by police officers.";
        itemSize[]={1,4};
    };
    class FieldShovel;
    class EG_Weapon_FieldShovel: FieldShovel {
        displayName="Field Shovel";
        descriptionShort="An entrenching tool. A collapsible spade used by military forces for a variety of purposes. Survivalists, freedivers, campers, hikers and other outdoor groups have found it to be indispensable in field use.";
        itemSize[]={2,4};
    };

    // Colourful Blades!!!!
    class CombatKnife;
    class WWB_CombatKnife_FiligreePurple: CombatKnife {
        hiddenSelections[]={"zbytek"};
        hiddenSelectionsTextures[]={"\Overgrown\data\weapon\melee\CombatKnife_FiligreePurple_co.paa"};
    }

    class Iceaxe;
    class WWB_Iceaxe_Blue: Iceaxe {
        hiddenSelections[]={"zbytek"};
        hiddenSelectionsTextures[]={"\Overgrown\data\weapon\melee\Iceaxe_Blue_co.paa"};
    }
    class WWB_Iceaxe_Green: Iceaxe {
        hiddenSelections[]={"zbytek"};
        hiddenSelectionsTextures[]={"\Overgrown\data\weapon\melee\Iceaxe_Green_co.paa"};
    }
    class WWB_Iceaxe_Purple: Iceaxe {
        hiddenSelections[]={"zbytek"};
        hiddenSelectionsTextures[]={"\Overgrown\data\weapon\melee\Iceaxe_Purple_co.paa"};
    }
    class WWB_Iceaxe_Red: Iceaxe {
        hiddenSelections[]={"zbytek"};
        hiddenSelectionsTextures[]={"\Overgrown\data\weapon\melee\Iceaxe_Red_co.paa"};
    }

    class Machete;
    class WWB_Machete_DamascusBlue: Machete {
        hiddenSelections[]={"zbytek"};
        hiddenSelectionsTextures[]={"\Overgrown\data\weapon\melee\CombatKnife_DamascusBlue_co.paa"};
    }
    class WWB_Machete_DamascusBurnt: Machete {
        hiddenSelections[]={"zbytek"};
        hiddenSelectionsTextures[]={"\Overgrown\data\weapon\melee\CombatKnife_DamascusBurnt_co.paa"};
    }
    class WWB_Machete_DamascusGreen: Machete {
        hiddenSelections[]={"zbytek"};
        hiddenSelectionsTextures[]={"\Overgrown\data\weapon\melee\CombatKnife_DamascusGreen_co.paa"};
    }
    class WWB_Machete_DamascusRed: Machete {
        hiddenSelections[]={"zbytek"};
        hiddenSelectionsTextures[]={"\Overgrown\data\weapon\melee\CombatKnife_DamascusRed_co.paa"};
    }
};
class CfgAmmo {
    class MeleeMeatTenderizer;
    class MeleeMace: MeleeMeatTenderizer {
        affectSkeleton=0.75;
        class DamageApplied {
            type="Melee";
            class Health {
                damage=25;
            };
            class Blood {
                damage=0;
            };
            class Shock {
                damage=30;
            };
            additionAnimalMeleeMultiplier=2;
        };
    };
    class MeleeFireExtinguisher: MeleeDamage {
        class DamageApplied {
            type="Melee";
            class Health {
                damage=10;
            };
            class Blood {
                damage=0;
            };
            class Shock {
                damage=35;
            };
            additionAnimalMeleeMultiplier=2;
        };
    };
    class MeleeDamage;
    class MeleeWoodBlunt: MeleeDamage {
        class DamageApplied {
            type="Melee";
            class Health {
                damage=15;
            };
            class Blood {
                damage=0;
            };
            class Shock {
                damage=30;
            };
            additionAnimalMeleeMultiplier=2;
        };
    };
};